server:
  port: 5555

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./gateway.db;AUTO_SERVER=TRUE
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  application:
    name: gateway-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8890/eureka/
    enabled: true

app:
  jwt:
    secret: RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!
    expiration-in-ms: 86400000

# for communicate with other services must be same
service:
  security:
    secure-key-username: test
    secure-key-password: 123456

book:
  service:
    url: http://localhost:8888

purchase:
  service:
    url: http://localhost:8889

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG